ci: update CI to check test and use the report files

diff --git a/.github/workflows/code-quality-on-pr.yml b/.github/workflows/code-quality-on-pr.yml
--- a/.github/workflows/code-quality-on-pr.yml
+++ b/.github/workflows/code-quality-on-pr.yml
@@ -1,52 +1,119 @@
-name: Code Quality on PR
+name: Code Quality and Test on PR
 
 on:
-  push:
-    branches:
-      - develop
   pull_request:
-    types: [opened, synchronize, reopened]
+    branches: [ develop ]
+    types: [ opened, synchronize, reopened ]
 
 jobs:
-  lint:
+  lint-and-test:
     runs-on: ubuntu-latest
     permissions:
       contents: write
       pull-requests: write
 
     steps:
-      - name: Code checkout
+      - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Setup nodejs
+      - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '22.13'
+          node-version: '22.13.1'
 
-      - name: Install dependencies
+      - name: Install Root Dependencies
         run: npm install
 
-      - name: Execute ESLint
-        id: eslint
-        run: npx eslint app/src/**/*.ts > eslint-report.txt || true
+      - name: Install App Dependencies
+        run: npm install
+        working-directory: app
 
-      - name: Check if ESLint report is empty
-        id: check_empty
+      - name: Execute ESLint
+        run: npm run eslint:report || true
+
+      - name: Check for Tests
+        id: check_tests
         run: |
-          if [ ! -s eslint-report.txt ]; then
-            echo "No linting issues found." > eslint-report.txt
+          if [ -d "app/test" ] && [ "$(ls -A app/test)" ]; then
+            echo "tests_exist=true" >> $GITHUB_ENV
+          else
+            echo "tests_exist=false" >> $GITHUB_ENV
           fi
 
-      - name: Load report ESLint
+      - name: Execute Tests (Mochawesome)
+        if: env.tests_exist == 'true'
+        run: npm run test:report
+        working-directory: app
 
+      - name: Upload ESLint Report
+        if: always()
         uses: actions/upload-artifact@v4
-
         with:
           name: eslint-report
-          path: eslint-report.txt
+          path: report/lint-report.txt
 
-      - name: Comment PR with ESLint report
+      - name: Upload Mochawesome HTML Report
+        if: failure() && env.tests_exist == 'true'
+        uses: actions/upload-artifact@v4
+        with:
+          name: mochawesome-html-report
+          path: app/reports/test-report.html
+
+      - name: Upload Readable Test Report
+        if: env.tests_exist == 'true'
+        uses: actions/upload-artifact@v4
+        with:
+          name: readable-test-report
+          path: app/reports/test-report.txt
+
+      - name: Set ESLint Report Message
+        id: set_eslint_report_message
+        run: |
+          if [ -f "report/lint-report.txt" ]; then
+            if [ -s "report/lint-report.txt" ]; then
+              echo "message<<EOF" >> $GITHUB_OUTPUT
+              cat report/lint-report.txt
+              echo "EOF" >> $GITHUB_OUTPUT
+            else
+              echo "message=No lint errors found." >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "message=No ESLint report found." >> $GITHUB_OUTPUT
+          fi
+
+      - name: Set Test Report Message
+        id: set_test_report_message
+        run: |
+          if [ "${{ env.tests_exist }}" == "true" ]; then
+            if [ -f "app/reports/test-report.txt" ]; then
+              echo "message=$(cat app/reports/test-report.txt)" >> $GITHUB_OUTPUT
+              echo "html_link=• [View Detailed HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_OUTPUT
+            else
+              echo "message=Tests have failed. Please check the artifacts for more details." >> $GITHUB_OUTPUT
+              echo "html_link=• [View Detailed HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "message=No tests found." >> $GITHUB_OUTPUT
+            echo "html_link=" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Comment PR with ESLint Report
+        if: always()
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          path: eslint-report.txt
+          header: "ESLint Report"
+          message: |
+            ```diff
+            ${{ steps.set_eslint_report_message.outputs.message }}
+            ```
+
+      - name: Comment PR with Test Report
+        if: always()
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          header: "Test Report"
+          message: |
+            ${{ steps.set_test_report_message.outputs.message }}
+            ${{ steps.set_test_report_message.outputs.html_link }}
